### ISSUE TITLE
打开指定文件夹

### ISSUE THREAD

**Issue by Hunlongyu** [Teal/TUtils#1]
看了一下好像没有打开文件夹的功能

```js
fs.openDir(path) {}
```

可以增加这个功能吗？

**Comment by xuld** [comment]
你是指读取文件夹下的所有文件吗？

如果只读取直接的一级，用 `fs.readDir('path/to/dir')`

如果希望遍历每一级，用 
```js
fs.walk('path/to/dir', { 
   dir(p){ console.log(p) },
   file(p){ console.log(p) },
})
```

多数情况你可能只需要遍历所有文件，可以用 `fs.glob('dir/**/*.{js,ts}')` 快速扫描所有文件

**Comment by Hunlongyu** [comment]
哈哈，不是读取文件夹里的文件，就是单纯的打开文件资源管理器。

应用场景如：
1. 打开下载文件所在的目录
2. 打开自动保存的文件所在的目录

**Comment by xuld** [comment]
这个不属于fs层的功能，你需要调用shell命令，可以用这个：

```js
var {exec} = require('tutils/process')

var dir = `C:\\Program Files`
exec(`explorer "${dir}"`)
```

**Comment by Hunlongyu** [comment]
1
